# Generated by Django 5.2.4 on 2025-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True,
                help_text="Введите Ваш ID в телеграме",
                max_length=150,
                null=True,
                verbose_name="ID в телеграме",
            ),
        ),
    ]
