# Generated by Django 5.2.4 on 2025-08-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                blank=True, help_text="Введите Ваш ID чата", max_length=150, null=True, verbose_name="ID чата"
            ),
        ),
    ]
