# Generated by Django 5.2.4 on 2025-08-03 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "place",
                    models.CharField(
                        help_text="Введите место, в котором необходимо выполнять привычку",
                        max_length=100,
                        verbose_name="место выполнения",
                    ),
                ),
                (
                    "time_to_do",
                    models.TimeField(
                        help_text="Введите время, когда необходимо выполнять привычку", verbose_name="время выполнения"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Введите действие, которое представляет собой привычка",
                        max_length=500,
                        verbose_name="действие",
                    ),
                ),
                (
                    "frequency",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Задайте периодичность повторения привычки (в днях)",
                        verbose_name="периодичность (в днях)",
                    ),
                ),
                (
                    "tag_pleasant_habit",
                    models.BooleanField(
                        default=False,
                        help_text="Привычка является приятной?",
                        verbose_name="признак приятной привычки",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        help_text="Введите вознаграждение", max_length=300, verbose_name="вознаграждение"
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        help_text="Задайте время на выполнение привычки (в секундах)",
                        verbose_name="время на выполнение (в секундах)",
                    ),
                ),
                (
                    "tag_public",
                    models.BooleanField(
                        default=True,
                        help_text="Могут ли другие пользователи видеть привычку?",
                        verbose_name="признак публичности",
                    ),
                ),
                (
                    "linked_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Задайте привычку-вознаграждение",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
