# Generated by Django 5.2.4 on 2025-08-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True,
                help_text="Введите вознаграждение",
                max_length=300,
                null=True,
                verbose_name="вознаграждение",
            ),
        ),
    ]
