# Generated by Django 5.2.4 on 2025-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_alter_habit_reward"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveIntegerField(
                help_text="Задайте периодичность повторения привычки (в днях)", verbose_name="периодичность (в днях)"
            ),
        ),
    ]
